### ISSUE TITLE
走評估 test_dir 會有其它的 input嗎？除了 data/train_dev

### ISSUE THREAD

**Issue by leo424y** [twgo/siann1-hak8_boo5-hing5#19]
`RUN bash -c 'time bash -x 走評估.sh data/lang_free data/train_dev'`

- 目前 $2 除了 data/train_dev  會有其它的 input嗎？

發現

lang=$1 # data/lang_free
if [ $# != 2 ]; then
  test_dir=data/dev
else
  test_dir=$2
fi

這段是要避免沒有$2時少了 test_dir

**Comment by sih4sing5hong5** [comment]
聲學模型試驗 會用著

**Comment by leo424y** [comment]
OK. 走評估.sh 在聲學模型試驗也會用到
