### ISSUE TITLE
走評估 $STAGE 判斷式

### ISSUE THREAD

**Issue by leo424y** [twgo/siann1-hak8_boo5-hing5#20]
stage=0

if [ $STAGE -le 6 10 11 的時候會做一些事 ]; then

但沒看到stage在哪有變化，這些if 應都是 0小於等於6/10/11都成立

請問用意為何？

**Comment by sih4sing5hong5** [comment]
若實驗改nuā，方便對死去ê所知重走

**Comment by leo424y** [comment]
原來手動控制用，debug技巧！
