### ISSUE TITLE
走評估變數定義

### ISSUE THREAD

**Issue by leo424y** [twgo/siann1-hak8_boo5-hing5#21]
有stage nj 兩個變數，請教其意味？
stage應是實驗階斷，推測往看可以了解，nj有點難猜

**Comment by leo424y** [comment]
cat 走評估.sh | grep 'nj'
nj=4
  steps/make_mfcc.sh --nj $nj --cmd "$train_cmd" \
    steps/decode_si.sh --nj $nj --cmd "$decode_cmd" --config conf/decode.config \
    steps/decode.sh --nj $nj --cmd "$decode_cmd" --config conf/decode.config \
    steps/decode.sh --nj $nj --cmd "$decode_cmd" --config conf/decode.config \
    steps/decode_fmllr.sh --nj $nj --cmd "$decode_cmd" \
    steps/decode_fmllr.sh --nj $nj --cmd "$decode_cmd" \

 請教nj意涵，似乎與decode這件事有關

- 何謂decode？
- make_mfcc  也是種decode？

**Comment by sih4sing5hong5** [comment]
nj = number of job = thread 數量 =  CPU 數量

[佮split有關](https://github.com/twgo/siann1-hak8_boo5-hing5/issues/14#issuecomment-390196019)


> make_mfcc

音檔=> mfcc

>decode

MFCC=> 辨識結果
