### ISSUE TITLE
走評估的wait

### ISSUE THREAD

**Issue by leo424y** [twgo/siann1-hak8_boo5-hing5#27]
# 發現
tri1-4被()括起
後面有個wait，但沒有看到 & 符號產生子行程

# 請問
- tri1-4是同步進行的意思嗎？
- wait是在等它們都結束才exit？

# 根據
https://blog.gtwang.org/programming/bash-tutorial-parallel-subprocesses-and-wait/

**Comment by sih4sing5hong5** [comment]
舊的`()`後有`&`，尾仔因為log傷亂，會看無，所以就共`&提掉`，`wait`就袂記得提掉
