### ISSUE TITLE
走訓練的準備 1,2

### ISSUE THREAD

**Issue by leo424y** [twgo/siann1-hak8_boo5-hing5#28]
發現 
- utt2spk_to_spk2utt.pl 產生spk2utt 
- 走評估沒有 prepare_lang ，有spk2utt，有make mfcc

---

問題
- spk2utt 沒有斷行，是因為要給機器看？kaldi原來的設計？
- 先刪 data/lang_train 再 prepare_lang 也是穩定性考量？ or 初始化？

---

if [ $STAGE -le 1 ]; then
  utils/utt2spk_to_spk2utt.pl data/train/utt2spk > data/train/spk2utt
fi

---
 
if [ $STAGE -le 2 ]; then
  rm -rf data/lang_train
  mkdir -p data/tmp
  utils/prepare_lang.sh data/local/dict "<UNK>"  data/tmp/lang_train data/lang_train
fi

**Comment by sih4sing5hong5** [comment]
> spk2utt 沒有斷行，是因為要給機器看？kaldi原來的設計？

著，`kaldi原來的設計`

> 先刪 data/lang_train 再 prepare_lang 也是穩定性考量？ or 初始化？

著，以早若無thai，更新了程式會死去
