### ISSUE TITLE
走訓練 basic training on MFCC features 10-15

### ISSUE THREAD

**Issue by leo424y** [twgo/siann1-hak8_boo5-hing5#30]
發現
- tri1前還有個mono 
- 由 train_mono.sh 伴 train_cmd即run.pl,    data/train, data/lang_train 輸出至 exp/mono
- mono align_si, train_deltas 產生 tri1接著tri2 tri3 tri4
-  看都有tri5 前面exit0
- STAGE 16的 train_cleaned看起來是要用clean_and_segment_data準備不同的data/train 

 請問 
- align_si(mono-tri3)/align_fmllr(tri4), train_deltas(產生tri1,tri2), train_lda_mllt(tri3), train_sat(tri4)似乎為訓練核心，依序讓model越來越強大，其中有需要自己調教的部分嗎？
- 應還有更多script 能讓model更強？隊長大能錯誤率超越前人可能是因為更多的tri？(tri5...)
- align_si 說明為算出 training alignments ，字面為 訓練路線，請教其意涵？
- train_deltas 將產出delta與delta-delta features 到 exp/triX ，有查到它能加強辨識表現，請教其意涵？
- train_deltas 的兩參數 <num-leaves> <tot-gauss> 3000 30000是固定的嗎？或有其它變因會影響它們？
- 了解 高斯函數 或其它數學對目前實驗有幫助嗎？ 我實在太久沒算，數學都還老師了XD
- 若不懂公式也能用kaldi訓練模型？是不是要加強「機率」這部分？有問到數學系朋友說「了解HMM要把握一個主軸, 就是慢慢把 "機率" 和 "統計" 看成兩種東西, 也就是在機率上面 play 更多東西, 但和統計比較無關...」
- if [ $STAGE -le 16, 19 ]; then 是隊長未來還會試的訓練嗎？

參考
```

# align_si
# Computes training alignments using a model with delta or LDA+MLLT features.

# train_deltas
 "Usage: steps/train_deltas.sh <num-leaves> <tot-gauss> <data-dir> <lang-dir> <alignment-dir> <exp-dir>" 
# GMM Acoustic model parameters
numLeaves=3000
numGauss=30000
echo "$0: Done training system with delta+delta-delta features in $dir"

# delta+delta-delta features
It turns out that calculating the MFCC trajectories and appending them to the original feature vector increases ASR performance by quite a bit (if we have 12 MFCC coefficients, we would also get 12 delta coefficients, which would combine to give a feature vector of length 24).

http://practicalcryptography.com/miscellaneous/machine-learning/guide-mel-frequency-cepstral-coefficients-mfccs/#deltas-and-delta-deltas

# train_lda_mllt
# LDA+MLLT refers to the way we transform the features after computing
# the MFCCs: we splice across several frames, reduce the dimension (to 40
# by default) using Linear Discriminant Analysis), and then later estimate,
# over multiple iterations, a diagonalizing transform known as MLLT or STC.
# See http://kaldi-asr.org/doc/transform.html for more explanation.

# train_sat
# This does Speaker Adapted Training (SAT), i.e. train on
# fMLLR-adapted features.  It can be done on top of either LDA+MLLT, or
# delta and delta-delta features.  If there are no transforms supplied
# in the alignment directory, it will estimate transforms itself before
# building the tree (and in any case, it estimates transforms a number
# of times during training).

# align_fmllr
# Computes training alignments; assumes features are (LDA+MLLT or delta+delta-delta)
# + fMLLR (probably with SAT models).
# It first computes an alignment with the final.alimdl (or the final.mdl if final.alimdl
# is not present), then does 2 iterations of fMLLR estimation.

# If you supply the --use-graphs option, it will use the training
# graphs from the source directory (where the model is).  In this
# case the number of jobs must match the source directory.


```

**Comment by sih4sing5hong5** [comment]
這篇問題傷濟矣@@


> align_si(mono-tri3)/align_fmllr(tri4), train_deltas(產生tri1,tri2), train_lda_mllt(tri3), train_sat(tri4)似乎為訓練核心，依序讓model越來越強大，其中有需要自己調教的部分嗎？
> train_deltas 的兩參數 <num-leaves> <tot-gauss> 3000 30000是固定的嗎？或有其它變因會影響它們？
就是這兩个參數 https://hackmd.io/s/rJXNcesr-#mono-phones-bi-phnoes-tri-phones

> 應還有更多script 能讓model更強？隊長大能錯誤率超越前人可能是因為更多的tri？(tri5...)
抄swbd的script，這馬攏是dnn才有變化，GMM就是這四五步

- train_deltas 將產出delta與delta-delta features 到 exp/triX ，有查到它能加強辨識表現，請教其意涵？

https://hackmd.io/s/rJXNcesr-#kaldi%E7%9A%84%E8%A8%93%E7%B7%B4%E6%B5%81%E7%A8%8B


- align_si 說明為算出 training alignments ，字面為 訓練路線，請教其意涵？

決定一句話，第幾秒到第幾秒是a,i...
https://zh.wikipedia.org/wiki/%E6%9C%80%E5%A4%A7%E6%9C%9F%E6%9C%9B%E7%AE%97%E6%B3%95
這需要看HTK book較清楚

- 了解 高斯函數 或其它數學對目前實驗有幫助嗎？ 我實在太久沒算，數學都還老師了XD

你若有興趣會當看

- 若不懂公式也能用kaldi訓練模型？是不是要加強「機率」這部分？有問到數學系朋友說「了解HMM要把握一個主軸, 就是慢慢把 "機率" 和 "統計" 看成兩種東西, 也就是在機率上面 play 更多東西, 但和統計比較無關...」

HTK book嘛有解釋

- if [ $STAGE -le 16, 19 ]; then 是隊長未來還會試的訓練嗎？

著，應該會試nnet3

**Comment by leo424y** [comment]
感謝詳解，看來HTK book是關鍵，我來加強，太多問題毛病我再改進。
