### ISSUE TITLE
 Day 26：自動語音識別(Automatic Speech Recognition) -- 觀念與實踐(續)

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/siann1-hak8_boo5-hing5#32]
https://ithelp.ithome.com.tw/articles/10195970

**Comment by leo424y** [comment]
哇！一目暸然，感謝補充，我再往HTK book看去。

**Comment by leo424y** [comment]
http://mirlab.org/jang/books/audioSignalProcessing/ 裡頭翻到，覺得不賴
