### ISSUE TITLE
manage.py 後面下的參數是跑哪個script呢?

### ISSUE THREAD

**Issue by leo424y** [twgo/siann1-hak8_boo5-hing5#37]
https://github.com/twgo/siann1-hak8_boo5-hing5/blob/5e829d4a494e127b58e8e1ca754b3a027b70b6dd/Dockerfile#L85-L88

```
RUN python3 manage.py 轉Kaldi音節text 臺語 $KALDI_S5C/data/train/ $KALDI_S5C/data/train_free
RUN python3 manage.py 轉Kaldi音節fst 臺語 拆做聲韻莫調 $KALDI_S5C/twisas-text $KALDI_S5C
```
manage.py 後面下的參數是跑哪個script呢？暫找不到

**Comment by sih4sing5hong5** [comment]
https://github.com/i3thuan5/tai5-uan5_gian5-gi2_hok8-bu7/tree/master/%E8%87%BA%E7%81%A3%E8%A8%80%E8%AA%9E%E6%9C%8D%E5%8B%99/management/commands

**Comment by leo424y** [comment]
啊哈，感謝隊長神速回覆
