### ISSUE TITLE
tw01+tw02報告

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/siann1-hak8_boo5-hing5#39]
| 實驗 | 說明| TW01Test SER(%) | 實驗編號 |
| -------- | -------- |------ | -------- |
| Ricer    | 音節數 1111通用  | 42.74 |
| tw01+tw02_thong  |  保留通用全部音節數1107  |  35.39     | #43 |
| tw01+tw02  |  符合臺羅音節數 940  |  用新的 ~~34.72~~ | ~~#47~~   |

**Comment by leo424y** [comment]
##### tw01+tw02, free-syllable-tw01test-仝語者測試
| 分支 |  ER% | 說明 | # |
| ------ | ----------- | --- | --- |
| \_thong	 | 35.39 | 保留通用全部音節數1107 | #75 |
| tw01+tw02	 | 35.53 | 符合臺羅音節數 940 | #74 |
| \_perturb	 | 34.16 | 調語速製作3倍音檔 | #64 |
| \_cleanup	 | 35.14 | 音檔擇優 | #65 |
| Ricer  | 42.74 | 音節數 1111通用 |  |

#### 不同語料測試結果比較
| 分支 |  ER% | # |
| ------ | ----------- | --- |
| tw01	 | 35.37 | #71 |
| tw01+tw02	 | 35.53 | #74 |
| twisas+tw01+tw02 | 41.62 | #70 |
| twisas+tw01	| 49.16 | #71 |
| twisas		 | 122.3 | #68 |
