### ISSUE TITLE
8k 訓練該改哪個wav.scp呢？

### ISSUE THREAD

**Issue by leo424y** [twgo/siann1-hak8_boo5-hing5#45]
https://github.com/twgo/gi2-gian5_boo5-hing5/blob/917da6a8e530f15355d5d73bef1b224e7921c97d/Dockerfile#L24

**Comment by leo424y** [comment]
試了 tshi3/train/wav.scp , data/train/wav.scp  跑出來結果都一樣，好像不大對

**Comment by leo424y** [comment]
是tshi3/train_free/wav.scp ?

**Comment by sih4sing5hong5** [comment]
對`走評估.sh`的對象做

**Comment by leo424y** [comment]
OK 那這個實驗對象用的是 tshi3/train_free/wav.scp 
已跑完，整理中
