### ISSUE TITLE
8k a-law, u-law 混合訓練

### ISSUE THREAD

**Issue by leo424y** [twgo/siann1-hak8_boo5-hing5#50]
請問隊長

對於老們說的8k a-law, u-law 混合訓練

我一樣是在 wav.scp 轉檔scirpt操作嗎

例如將半數的wav  a-law化，另半數的wav  u-law  化 

還是有更好的做法？

**Comment by sih4sing5hong5** [comment]
類似perturb複製一份

一份原樣，一份a-law，一份u-law，攏總3份

**Comment by leo424y** [comment]
收到，原來如此！  #51
