### ISSUE TITLE
8k  data train 順序修正

### ISSUE THREAD

**Issue by leo424y** [twgo/siann1-hak8_boo5-hing5#52]
順序修正如：
https://github.com/twgo/siann1-hak8_boo5-hing5/blob/tw01%2Btw02_8k/Dockerfile

請丞宏review 謝謝

**Comment by leo424y** [comment]
#47 試了把轉檔script移到copy之前，成功拿掉 downsample ，訓練結果無太大差異，後面8k a-law ，u-law會陸續補上

**Comment by sih4sing5hong5** [comment]
review OK
