### ISSUE TITLE
重跑16K tw01 tw02 仝語者 結果相同

### ISSUE THREAD

**Issue by leo424y** [twgo/siann1-hak8_boo5-hing5#56]
結果為141發現與74皆為最新版本 SER 為 35.53
皆為接siann1-hak8_boo5-hing5:62
FROM localhost:5000/siann1-hak8_boo5-hing5:62  (tw01+02 最新版)

141
https://github.com/twgo/gi2-gian5_boo5-hing5/blob/edfb881004b69dced8af26e286bab34127309569/Dockerfile

74
https://github.com/twgo/gi2-gian5_boo5-hing5/blob/702eefcb53ff28c89408244bbca8728d7cbb4def/Dockerfile

**Comment by sih4sing5hong5** [comment]
好～
